### ISSUE TITLE
UI doesn't work

### ISSUE THREAD

**Issue by sardaukar** [ParthSareen/RAG-in-a-box#1]
Launching the UI with

```
python3 src/rag_in_a_box/interface.py
```

Results in

```
Traceback (most recent call last):
  File "/Users/bruno.antunes/Code/FOREIGN/RAG-in-a-box/src/rag_in_a_box/interface.py", line 3, in <module>
    from main import load_documents
  File "/Users/bruno.antunes/Code/FOREIGN/RAG-in-a-box/src/rag_in_a_box/main.py", line 6, in <module>
    from common_utils import store_documents, search_documents, process_search_results, load_documents
  File "/Users/bruno.antunes/Code/FOREIGN/RAG-in-a-box/src/rag_in_a_box/common_utils.py", line 4, in <module>
    from rag_in_a_box.loaders.pdf_loader import PdfLoader
  File "/Users/bruno.antunes/Code/FOREIGN/RAG-in-a-box/src/rag_in_a_box/loaders/pdf_loader.py", line 4, in <module>
    from icecream import ic
ModuleNotFoundError: No module named 'icecream'
```

On macOS

**Comment by ParthSareen** [comment]
Fixed!
https://github.com/ParthSareen/RAG-in-a-box/pull/2
